### ISSUE TITLE
[Enhancement]Improvement in the UI/UX for the Login and Registration Component 

### ISSUE THREAD

**Issue by Keyuri-19** [Sejal99/blogging-site#67]
The the User Interface for the Registration and the Login Page is very much basic and not that much interactive.
I will Improve the User Interface for the same and will make it more Eye-catchy than it is currently.

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
I would really like to work on this issue, so please assign it to me.

**Comment by MOHINI1403** [comment]
Hello I would love to work on this issue.
The UI of the register and login page could be improved a lot better and since you are using Next.Js as per that we can use additional add on functionalities of next js like URL State Management to improve the user experience.
I worked with such issue earlier so I think i could work on this issue and resolve it to the quickest.
I would love to collaborate with you if you want me to contribute on this issue please assign this issue to me 
I will share further details further on how I will be working on this
