### ISSUE TITLE
Search blogs by categories

### ISSUE THREAD

**Issue by a5hwarya5** [Sejal99/blogging-site#68]
Category based searching can improve the user experience.

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.

Sir, I would really like to work on this issue, so please assign it to me.

**Comment by MOHINI1403** [comment]
Hello I would love to work on this issue to sort the blogs based on the category we can we do a lot of things to improve this by using collaborative filtering techniques and boosting the overall model .I would also love to deliever the documentation on how to do this .
Looking forward to collab with you and work on this issue.
I would request to please assign me the issue so that I could start working on it.
